# Module 3 - Scientific Data Manipulation
## 1. NumPy and Vectorization

Welcome to the first notebook of Module 3. In this notebook, we introduce **NumPy** and the idea of **vectorized computation**.

NumPy is one of the most important libraries in scientific Python. It allows us to work with collections of numbers efficiently and clearly. Instead of processing one value at a time in a loop, we can often apply one operation to a whole array at once.

The examples in this notebook use simple environmental measurements such as temperature, humidity, and wind speed.

### Learning goals

By the end of this notebook, you should be able to:

- create and inspect NumPy arrays,
- understand why arrays are useful in scientific work,
- perform vectorized calculations,
- use boolean masks to filter values,
- compute simple summary statistics,
- work with missing values represented by `NaN`.


## 1.1 Importing NumPy and Creating Arrays

A NumPy array is similar to a Python list, but it is designed for numerical work. Arrays usually contain elements of the same data type, and NumPy provides many operations that work directly on the whole array.


In [1]:
import numpy as np


In [2]:
temperature_c = np.array([18.5, 19.2, 20.1, 21.3, 22.0, 21.6, 20.4])
humidity = np.array([65, 63, 60, 58, 57, 59, 61])

print("Temperature readings:", temperature_c)
print("Humidity readings:", humidity)


Temperature readings: [18.5 19.2 20.1 21.3 22.  21.6 20.4]
Humidity readings: [65 63 60 58 57 59 61]


It is often useful to inspect the structure of an array. The **shape** tells us how many elements or dimensions it has, while the **data type** tells us how the values are stored.


In [3]:
print("Array type:", type(temperature_c))
print("Shape:", temperature_c.shape)
print("Number of dimensions:", temperature_c.ndim)
print("Data type:", temperature_c.dtype)
print("Number of elements:", temperature_c.size)


Array type: <class 'numpy.ndarray'>
Shape: (7,)
Number of dimensions: 1
Data type: float64
Number of elements: 7


## 1.2 Python Lists vs NumPy Arrays

For beginners, NumPy becomes easier to understand when we compare it with plain Python lists.

Lists are flexible and useful for general programming. NumPy arrays are more suitable for scientific data because mathematical operations are simpler and faster.


In [4]:
temperature_list = [18.5, 19.2, 20.1, 21.3]
temperature_array = np.array(temperature_list)

print("Python list:", temperature_list)
print("NumPy array:", temperature_array)


Python list: [18.5, 19.2, 20.1, 21.3]
NumPy array: [18.5 19.2 20.1 21.3]


In [5]:
# With a Python list, multiplication repeats the list
print("List * 2:", temperature_list * 2)

# With a NumPy array, multiplication is numerical
print("Array * 2:", temperature_array * 2)


List * 2: [18.5, 19.2, 20.1, 21.3, 18.5, 19.2, 20.1, 21.3]
Array * 2: [37.  38.4 40.2 42.6]


This small example shows a key advantage of NumPy: operations behave like mathematical operations, not like general-purpose list operations.


## 1.3 Element-wise Operations

A central idea in NumPy is that many operations are performed **element by element**. If two arrays have the same length, NumPy combines the first elements together, the second elements together, and so on.


In [6]:
temperature_k = temperature_c + 273.15
temperature_f = temperature_c * 9/5 + 32
difference_from_mean = temperature_c - np.mean(temperature_c)

print("Temperature in Kelvin:", np.round(temperature_k, 2))
print("Temperature in Fahrenheit:", np.round(temperature_f, 2))
print("Difference from average:", np.round(difference_from_mean, 2))


Temperature in Kelvin: [291.65 292.35 293.25 294.45 295.15 294.75 293.55]
Temperature in Fahrenheit: [65.3  66.56 68.18 70.34 71.6  70.88 68.72]
Difference from average: [-1.94 -1.24 -0.34  0.86  1.56  1.16 -0.04]


Because we apply the same operation to the whole array, the code stays short and easy to read.


## 1.4 Why Vectorization Matters

**Vectorization** means operating on a whole array at once instead of writing a loop that processes one value at a time.

In research code, vectorization is useful because it usually makes code:

- shorter,
- easier to understand,
- less error-prone,
- better suited for large datasets.


In [7]:
# Using a loop
fahrenheit_loop = []
for value in temperature_c:
    fahrenheit_loop.append(value * 9/5 + 32)

# Using vectorization
fahrenheit_vectorized = temperature_c * 9/5 + 32

print("Loop result:      ", np.round(fahrenheit_loop, 2))
print("Vectorized result:", np.round(fahrenheit_vectorized, 2))


Loop result:       [65.3  66.56 68.18 70.34 71.6  70.88 68.72]
Vectorized result: [65.3  66.56 68.18 70.34 71.6  70.88 68.72]


Both approaches give the same result. In scientific work, the vectorized version is usually preferred.


## 1.5 Summary Statistics

NumPy provides many functions for quick numerical summaries. These are often the first step when we inspect a dataset.


In [8]:
print("Mean temperature:", np.mean(temperature_c))
print("Minimum temperature:", np.min(temperature_c))
print("Maximum temperature:", np.max(temperature_c))
print("Standard deviation:", np.std(temperature_c))


Mean temperature: 20.442857142857147
Minimum temperature: 18.5
Maximum temperature: 22.0
Standard deviation: 1.1914662549710313


The standard deviation gives a simple measure of variability. A small value means the readings are close to each other. A larger value suggests more variation.


## 1.6 Boolean Masks

A **boolean mask** is an array of `True` and `False` values. It can be used to select only the observations that satisfy a condition.


In [9]:
warm_days = temperature_c > 20
print("Warm-day mask:", warm_days)
print("Temperatures above 20°C:", temperature_c[warm_days])


Warm-day mask: [False False  True  True  True  True  True]
Temperatures above 20°C: [20.1 21.3 22.  21.6 20.4]


In [10]:
comfortable_humidity = humidity >= 60
print("Humidity >= 60%:", humidity[comfortable_humidity])


Humidity >= 60%: [65 63 60 61]


Boolean masks are especially useful in scientific datasets when we want to focus on specific ranges, such as temperatures above a threshold or humidity below a target level.


## 1.7 Combining Conditions

We can combine multiple conditions with `&` (and), `|` (or), and `~` (not).

When combining conditions in NumPy, each comparison should usually be placed in parentheses.


In [11]:
good_conditions = (temperature_c > 20) & (humidity < 60)
print("Good-condition mask:", good_conditions)
print("Selected temperatures:", temperature_c[good_conditions])
print("Selected humidity values:", humidity[good_conditions])


Good-condition mask: [False False False  True  True  True False]
Selected temperatures: [21.3 22.  21.6]
Selected humidity values: [58 57 59]


This kind of filtering is common when researchers need to isolate periods that satisfy more than one requirement.


## 1.8 Working with Missing Values (`NaN`)

Scientific datasets often contain missing values. In NumPy, missing numerical values are commonly represented by `np.nan`.


In [12]:
temperature_with_nan = np.array([18.5, 19.2, np.nan, 21.3, 22.0, np.nan, 20.4])
print(temperature_with_nan)


[18.5 19.2  nan 21.3 22.   nan 20.4]


In [13]:
print("Mean with np.mean():", np.mean(temperature_with_nan))
print("Mean with np.nanmean():", np.nanmean(temperature_with_nan))

print("Maximum with np.max():", np.max(temperature_with_nan))
print("Maximum with np.nanmax():", np.nanmax(temperature_with_nan))


Mean with np.mean(): nan
Mean with np.nanmean(): 20.28
Maximum with np.max(): nan
Maximum with np.nanmax(): 22.0


Regular functions such as `np.mean()` often return `nan` if missing values are present. NumPy therefore provides `nan`-aware functions such as:

- `np.nanmean()`
- `np.nanmin()`
- `np.nanmax()`
- `np.nansum()`

These are very useful when missing values should be ignored temporarily.


## 1.9 A Small 2D Example

Arrays do not need to be one-dimensional. They can also represent tables or matrices.

Here is a small 2D array where rows correspond to days and columns correspond to variables.


In [14]:
measurements = np.array([
    [18.5, 65, 3.2],
    [19.2, 63, 4.1],
    [20.1, 60, 5.8],
    [21.3, 58, 6.3]
])

print(measurements)
print("Shape:", measurements.shape)


[[18.5 65.   3.2]
 [19.2 63.   4.1]
 [20.1 60.   5.8]
 [21.3 58.   6.3]]
Shape: (4, 3)


In [15]:
print("First row:", measurements[0])
print("Second column (humidity):", measurements[:, 1])
print("Last two rows:", measurements[2:])


First row: [18.5 65.   3.2]
Second column (humidity): [65. 63. 60. 58.]
Last two rows: [[20.1 60.   5.8]
 [21.3 58.   6.3]]


This is a useful bridge between NumPy arrays and tabular structures. Later, in Pandas, we will attach column names and richer functionality to this kind of data.


## 1.10 Guided Practice

Complete the tasks below.

1. Convert wind speed from m/s to km/h.
2. Create a mask for values above 20 km/h.
3. Compute the average wind speed in km/h.
4. Find the mean of the rainfall array while ignoring missing values.


In [16]:
wind_ms = np.array([3.2, 4.1, 5.8, 6.3, 4.9, 3.7, 7.1, 5.0])
rain_mm = np.array([0.0, 0.5, np.nan, 1.2, 0.0, np.nan, 2.1, 0.3])

wind_kmh = ...
strong_wind = ...
average_wind = ...
average_rain = ...

print("Wind in km/h:", wind_kmh)
print("Strong wind mask:", strong_wind)
print("Average wind speed:", average_wind)
print("Average rainfall:", average_rain)


Wind in km/h: Ellipsis
Strong wind mask: Ellipsis
Average wind speed: Ellipsis
Average rainfall: Ellipsis


### Suggested solution


In [17]:
wind_kmh = wind_ms * 3.6
strong_wind = wind_kmh > 20
average_wind = np.mean(wind_kmh)
average_rain = np.nanmean(rain_mm)

print("Wind in km/h:", np.round(wind_kmh, 2))
print("Strong wind mask:", strong_wind)
print("Average wind speed:", round(average_wind, 2))
print("Average rainfall:", round(average_rain, 2))


Wind in km/h: [11.52 14.76 20.88 22.68 17.64 13.32 25.56 18.  ]
Strong wind mask: [False False  True  True False False  True False]
Average wind speed: 18.05
Average rainfall: 0.68


## 1.11 Summary

In this notebook, you learned how to:

- create NumPy arrays,
- compare arrays with regular Python lists,
- perform vectorized numerical operations,
- compute basic summary statistics,
- filter values with boolean masks,
- combine multiple logical conditions,
- work with missing values using `NaN`,
- inspect a small two-dimensional array.

In the next notebook, we move from arrays to **Pandas DataFrames**, which are better suited for structured tabular data.
